//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_groups()
        {
            this.profiles = new HashSet<profiles>();
        }
    
        public int id_product_group { get; set; }
        public Nullable<int> id_product_group_source { get; set; }
        public string code { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public Nullable<int> id_ref_application { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profiles> profiles { get; set; }
    }
}
