//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {

        [Key]
        
        public int id_user { get; set; }
        public string trigram { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string type { get; set; }
        public string password { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<int> id_profile { get; set; }
    
        public virtual profiles profiles { get; set; }
       
    }
}
